spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8080
  ssl:
    key-store: classpath:springcloudserver.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: server
    enabled: true
eureka:
  instance:
    secure-port: 8080
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: https://spring-cloud-eureka-server-svc:${server.port}
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: spring-cloud-eureka

#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer1
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    serviceUrl:
#      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: peer3
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
