spring:
  application:
    name: spring-cloud-consumer
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: https://spring-cloud-eureka-server-svc:8080/eureka/
    registry-fetch-interval-seconds: 5

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  ServerListRefreshInterval: 30000

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: spring-cloud-consumer

ssl:
  key-store: springcloudclient.p12
  key-store-password: 123456
