spring:
  application:
    name: spring-cloud-consumer
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
