---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-provider-svc
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-cloud-provider

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-provider
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spring-cloud-provider
  template:
    metadata:
      labels:
        app: spring-cloud-provider
        namespace: default
    spec:
      containers:
        - name: spring-cloud-provider
          image: candyleer/spring-cloud-provider:v1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: tomcat
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
