spring:
  application:
    name: spring-cloud-provider
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://spring-cloud-eureka-server-svc:8080/eureka/
