spring:
  application:
    name: spring-cloud-provider
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://spring-cloud-eureka-server-svc:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: spring-cloud-provider
